# Generated by Django 4.2.30 on 2026-05-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalDexBinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalDexCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('tcg_image', models.URLField(blank=True, max_length=500)),
                ('tcg_set', models.CharField(blank=True, max_length=200)),
                ('tcg_card_id', models.CharField(blank=True, max_length=50)),
                ('tcg_local_id', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='national_dex.nationaldexbinder')),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
    ]
