# Generated by Django 4.2.30 on 2026-08-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_dex', '0003_pokemon_name_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationaldexcard',
            options={},
        ),
    ]
