# Generated by Django 4.2.30 on 2026-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_sets', '0002_mastersetcardvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSetTotalSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=50, unique=True)),
                ('total_slots', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
