# Generated by Django 4.2.30 on 2026-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombinder',
            name='page_count',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
